### ISSUE TITLE
Preprocess registrations at register time

### ISSUE THREAD

**Issue by noemi-salaun** [kaiu-lab/serializer#12]
Instead of using a dumb `Serializer.register()` that leaves all the bulk of the processing for when the serializer is used, I think we should move most of the processing during the registration.

Currently, `Serializer.register()` simply fills an array and checks for some little constraints. On the other side, `Serializer.deserialize()` process this array each time to find the correct inheritance or other stuff.

I would prefer to do most of the preprocessing at registration time, so `Serializer.deserialize()` has nothing else to do but actually deserializing.

Preprocessing in the `Serializer.register()` can also be used to check a certain number of inheritance constraints, to throw errors without having to wait for some `Serializer.deserialize()` calls.

**Comment by Supamiu** [comment]
I don't see what could be added at register time, mainly because the slowest part of the actual logic is the array processing in order to get the correct class constructor for the current object (with the predefined parent). 

Some checks might be moved to register time tho, like the inheritance one.
