### ISSUE TITLE
Add support for attributes name mapping

### ISSUE THREAD

**Issue by noemi-salaun** [kaiu-lab/serializer#17]
We should allow to map a json field into a class attribute with a differente name.

For exemple, the json may contain "prix", and the developper want to map it to the attribute "price" inside its class.

```typescript
class Foo {
   @Deserialize('prix')
   price: number;
}
```

**Comment by Supamiu** [comment]
I wonder how we should name this decorator, these are the ones I am thinking of:

- `@Alias`
- `@Name`
- `@FieldName`

**Comment by noemi-salaun** [comment]
We already have the decorator `@DeserializeAs()`, we should extends this use for all fields that need to be deserialized, and the decorator `@DeserializeAs()` and `@Deserialize()` can optionnaly set the field name

**Comment by Supamiu** [comment]
I agree but the name "Deserialize" is not that good for dev experience, I mean, it's not obvious that `@Deserialize('bar')` will use the json field name `bar` to retrieve value for thie field.

**Comment by noemi-salaun** [comment]
It's the same probleme for any function in any code ever written. You cannot indicate perfectly which params are expected base only on the function name :/

**Comment by Supamiu** [comment]
I'll implement this as `@Deserialize` but I don't think it's the best name for this decorator. However the name can be changed easily so...

**Comment by Supamiu** [comment]
There's a little issue with the decorator, when we iterate over fields, we iterate over `obj`'s fields because at this point, our result object is empty, so our only way to get all properties in an object is to iterate over `obj`'s properties.

Problem is that if we iterate over `obj`'s properties, we'll never check the actual property in the result instance, and we'll never see the decorator.

### Example:
```typescript
const obj = {foo: 'bar};
class Example {
    @Deserialize('foo')
    name: string;
}
```

When we iterate for properties, we do
```typescript
for(const prop in obj){
    //Iterations will go over obj's properties, not our result's properties, name property will never get checked.
}
```

### Possible solutions:

The actual solution I've found is to register on class's level our custom fields, using a decorator implementation like this: 

```typescript
export function Deserialize(fieldName: string): (...args: any[]) => void {
    return (target: any, propertyKey: string) => {
        const customFieldNames = Reflect.getMetadata('serializer:field:properties', target) || [];
        Reflect.defineMetadata('serializer:field:properties', customFieldNames.concat([propertyKey]), target);
        return Reflect.defineMetadata('serializer:field', fieldName, target, propertyKey);
    };
}
```

This allows to get a metadata value on the class itself, and this metadata contains a list of the custom fields of our object, an example method to get custom property mappings would be:

```typescript
const customProperties = Reflect.getMetadata('serializer:field:properties', target);
const propsMap = {};
for(const property of customProperties){
    propsMap[reflect.getMetadata('serializer:field', result[property])] = property;
}
```

Giving us something like that for the above example:
`{ foo: 'name' }`

Then we can iterate on this map to find field names.
