### ISSUE TITLE
Add support for serialization

### ISSUE THREAD

**Issue by noemi-salaun** [kaiu-lab/serializer#18]
With the aim of proposing a fully featured library, it would be necessary to manage the serialization in addition to the deserialization.

- Some projects may want to use this lib server side and need to serialize object instead of deserialize.
- We can think about a complexe serialization process before sending data with some Ajax call client side.

**Comment by Supamiu** [comment]
I think that the first think we may want to implement is a `@Transient` decorator, allowing a field to be deleted before serialization, to avoid sending critical informations (eg. passwords).

**Comment by Supamiu** [comment]
Another feature to implement should be the anti-recursion decorator.

### Example:
```typescript
let obj= {
    bla: 'bla',
    child: {
        foo: 'bar',
        parent: obj
    }
};
```

If you serialize this by recursion, you'll have a problem because each object references the other.

There's a simple solution: let JSON.stringify do the job since it'll remove the recursive part (example: https://repl.it/JjPh/0)

Another solution would be to allow it by adding a decorator, problem is that we'd have to implement the whole serialization logic just for this case (see [Jackson's example](https://stackoverflow.com/a/18288939/4102561)
